version: '2'
services:

  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 1 -ui-dir /ui"

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9997:9999"   # jmx
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.105
      KAFKA_CREATE_TOPICS: "collector-outbound-topic:1:1,flink-outbound-topic:1:1"
      JMX_PORT: 9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      - consul

  flink-jobmanager:
    image: flink
    container_name: flink-jobmanager
    ports:
      - "8081:8081"   # webui
      - "9999:9999"   # jmx
    command: jobmanager
    volumes:
      - /usr/local/flink/conf
      - ./infrastructure/logs/flink-jobmanager:/usr/local/flink/log
    depends_on:
      - consul
      - kafka
      - elk

  flink-taskmanager:
    image: flink
    container_name: flink-taskmanager
    ports:
      - "9998:9999"   # jmx
    command: taskmanager
    volumes_from:
      - flink-jobmanager
    depends_on:
      - flink-jobmanager
      - consul
      - kafka
      - elk

  elk:
    container_name: elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
    volumes:
      - ./infrastructure/logs/elk/elasticsearch:/var/log/elasticsearch
      - ./infrastructure/logs/elk/logstash:/var/log/logstash
      - ./infrastructure/logs/elk/kibana:/var/log/kibana
    depends_on:
      - zookeeper
      - kafka

  collector-manager:
    container_name: collector-manager
    image: io.thesis/collector-manager
    ports:
      - "9090:9090"
    depends_on:
      - consul
    environment:
      SERVER_PORT: 9090
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
