collector:
  jmx:
    url: service:jmx:rmi:///jndi/rmi://localhost:9999/jmxrmi
  client:
    default-interval-in-ms: 5000

server:
  port: ${CLIENT_PORT:9091}

logging:
  file: logs/collector-client.log
  level:
    io.thesis.collector: DEBUG
    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.kafka: INFO

kafka:
  broker:
    address: localhost:9092
  outbound-topic: collector-outbound-topic

spring:
  thymeleaf:
    cache: false
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true

info:
  arch: ${os.arch}
  os: ${os.name}
  version: ${os.version}